#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numactl
Version  : 2.0.13
Release  : 21
URL      : https://github.com/numactl/numactl/releases/download/v2.0.13/numactl-2.0.13.tar.gz
Source0  : https://github.com/numactl/numactl/releases/download/v2.0.13/numactl-2.0.13.tar.gz
Summary  : Simple NUMA policy support
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: numactl-bin = %{version}-%{release}
Requires: numactl-lib = %{version}-%{release}
Requires: numactl-license = %{version}-%{release}
Requires: numactl-man = %{version}-%{release}
BuildRequires : util-linux

%description
# numactl
[![Build Status](https://travis-ci.org/numactl/numactl.svg?branch=master)](https://travis-ci.org/numactl/numactl)

%package bin
Summary: bin components for the numactl package.
Group: Binaries
Requires: numactl-license = %{version}-%{release}

%description bin
bin components for the numactl package.


%package dev
Summary: dev components for the numactl package.
Group: Development
Requires: numactl-lib = %{version}-%{release}
Requires: numactl-bin = %{version}-%{release}
Provides: numactl-devel = %{version}-%{release}
Requires: numactl = %{version}-%{release}
Requires: numactl = %{version}-%{release}

%description dev
dev components for the numactl package.


%package lib
Summary: lib components for the numactl package.
Group: Libraries
Requires: numactl-license = %{version}-%{release}

%description lib
lib components for the numactl package.


%package license
Summary: license components for the numactl package.
Group: Default

%description license
license components for the numactl package.


%package man
Summary: man components for the numactl package.
Group: Default

%description man
man components for the numactl package.


%prep
%setup -q -n numactl-2.0.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571000569
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1571000569
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/numactl
cp %{_builddir}/numactl-2.0.13/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/numactl/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/numactl-2.0.13/LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/numactl/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/share/man/man2/move_pages.2

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/memhog
/usr/bin/migratepages
/usr/bin/migspeed
/usr/bin/numactl
/usr/bin/numademo
/usr/bin/numastat

%files dev
%defattr(-,root,root,-)
/usr/include/numa.h
/usr/include/numacompat1.h
/usr/include/numaif.h
/usr/lib64/libnuma.so
/usr/lib64/pkgconfig/numa.pc
/usr/share/man/man3/numa.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnuma.so.1
/usr/lib64/libnuma.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/numactl/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/numactl/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/memhog.8
/usr/share/man/man8/migratepages.8
/usr/share/man/man8/migspeed.8
/usr/share/man/man8/numactl.8
/usr/share/man/man8/numastat.8
