#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numactl
Version  : 2.0.11
Release  : 12
URL      : ftp://oss.sgi.com/www/projects/libnuma/download/numactl-2.0.11.tar.gz
Source0  : ftp://oss.sgi.com/www/projects/libnuma/download/numactl-2.0.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: numactl-bin
Requires: numactl-lib
Requires: numactl-doc
BuildRequires : util-linux

%description
Simple NUMA policy support. It consists of a numactl program to run
other programs with a specific NUMA policy and a libnuma shared library
("NUMA API") to set NUMA policy in applications.

%package bin
Summary: bin components for the numactl package.
Group: Binaries

%description bin
bin components for the numactl package.


%package dev
Summary: dev components for the numactl package.
Group: Development
Requires: numactl-lib
Requires: numactl-bin
Provides: numactl-devel

%description dev
dev components for the numactl package.


%package doc
Summary: doc components for the numactl package.
Group: Documentation

%description doc
doc components for the numactl package.


%package lib
Summary: lib components for the numactl package.
Group: Libraries

%description lib
lib components for the numactl package.


%prep
%setup -q -n numactl-2.0.11

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/memhog
/usr/bin/migratepages
/usr/bin/migspeed
/usr/bin/numactl
/usr/bin/numademo
/usr/bin/numastat

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
%doc /usr/share/man/man8/*
%exclude /usr/share/man/man2/move_pages.2

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
